config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :allowance_admin do 
  	post :update_allowance, on: :member
  end
  resources :allowance


  get "/art/in/:cat", to: 'art#index'
  get "/art/tagged/:tag", to: 'art#index'

  resources :art
  resources :art_admin do 
  	get :preview, on: :member
  	delete :empty_trash, on: :collection
  end

  get "/writings/in/:cat", to: 'writings#index'
  get "/writings/tagged/:tag", to: 'writings#index'

  resources :writings
  resources :writing_admin do 
  	get :preview, on: :member
  	delete :empty_trash, on: :collection
  end


  get '/about' => 'swell_media/static#about'

	devise_scope :user do
		get '/login' => 'sessions#new', as: 'login'
		get '/logout' => 'sessions#destroy', as: 'logout'
		get '/register' => 'registrations#new', as: 'register'
	end
	devise_for :users, :controllers => { :registrations => 'registrations', :sessions => 'sessions' }




  mount SwellMedia::Engine, :at => '/'
end

app/controllers/writings_controller.rb
class WritingsController < ApplicationController


	def index
		@tagged = params[:tagged]
		
		@category = SwellMedia::Category.friendly.find( params[:category] || params[:cat] ) if ( params[:category] || params[:cat] ).present?

		@title = @category.try(:name)
		@title ||= "Writings"

		@articles = SwellMedia::SearchService.search( SwellMedia::Article, category: @category, tags: @tagged )

		user_level = User.roles[current_user.try( :role )] || 0

		@articles = @articles.where( "availability <= :level", level: user_level )

		# set count before pagination
		@count = @articles.count

		@articles = @articles.page( params[:page] )

		set_page_meta title: @title, og: { type: 'blog' }, twitter: { card: 'summary' }
	end


	def show
		user_level = User.roles[current_user.try( :role )] || 0

		@articles = SwellMedia::Article.where( "availability <= :level", level: user_level )

		@article = @articles.friendly.find( params[:id] )

		
	end

end

app/views/writings/_row.html.haml
- cache( "row-#{article.cache_key}" ) do
	%div[article]{ style: 'margin-top:1em;margin-bottom:1em;'}
		.artile-title{ style: 'font-size:125%;'}
			= link_to article.title, writing_path( article )

		%span.pull-right
			= article.publish_at.strftime('%B %e, %Y')
		%hr
		.clearfix

app/views/writings/_sidebar.html.haml
.well
	%h4
		%a{ href: '/writings' }
			Writings

	- SwellMedia::ArticleCategory.all.each do |cat|
		.cat-list
			%a{ href: "/writings/in/#{cat.slug}" }
				= cat

app/views/writings/index.html.haml
.container
	.row{ style: 'margin-top:1em;' }
		.col-sm-3
			= render "sidebar"
		.col-sm-9
			- if @tagged.present?
				%h1{ style: 'font-size:200%;' }
					= pluralize @count, 'Writing'
					tagged
					= "'#{@tagged}'"

			- if @category.present?
				%h1{ style: 'font-size:200%;' }
					= pluralize @count, 'Writing'
					in
					= "'#{@category}'"

			= raw paginate @articles
			- @articles.each do |article|
				= render 'row', article: article
			= raw paginate @articles

app/views/writings/show.html.haml
- cache( @article ) do
	.container
		.row{ style: 'margin-top:1em;' }
			.col-sm-3
				= render "sidebar"
			.col-sm-9
				.single-post-w
					%h1.post-title
						= @article.title
					%p.post-info{ style: 'margin-top: -1em;' }
						%span.info-item
							= @article.publish_at.strftime('%B %e, %Y')
						- if @article.tags.present?
							%span.info-item
								Tagged:
								- @article.tags.each do |tag|
									%a.post-tag{ href: articles_path( tagged: tag.name ) }
										%span.label.label-info
											= tag.name
					- if @article.avatar.present?
						.post-avatar{ style: 'text-align:center;' }
							= image_tag @article.avatar, width: '75%'

					.post-content
						= raw @article.content