config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :allowance_admin do 
  	post :update_allowance, on: :member
  end
  resources :allowance


  get "/art/in/:cat", to: 'art#index'
  get "/art/tagged/:tag", to: 'art#index'

  resources :art
  resources :art_admin do 
  	get :preview, on: :member
  	delete :empty_trash, on: :collection
  end

  get "/writings/in/:cat", to: 'writings#index'
  get "/writings/tagged/:tag", to: 'writings#index'

  resources :writings
  resources :writing_admin do 
  	get :preview, on: :member
  	delete :empty_trash, on: :collection
  end


  get '/about' => 'swell_media/static#about'

	devise_scope :user do
		get '/login' => 'sessions#new', as: 'login'
		get '/logout' => 'sessions#destroy', as: 'logout'
		get '/register' => 'registrations#new', as: 'register'
	end
	devise_for :users, :controllers => { :registrations => 'registrations', :sessions => 'sessions' }




  mount SwellMedia::Engine, :at => '/'
end

app/controllers/allowance_admin_controller.rb
class AllowanceAdminController < ApplicationController
	layout 'admin'

	before_action 	:authenticate_user!
	before_action	:require_momdad
	before_action 	:get_transaction, only: [ :destroy, :edit, :update ]


	def create
		@transaction = Allowance.first.allowance_transactions.new( transaction_params )
		
		@transaction.amount = transaction_params[:amount].to_f * 100

		@transaction.save
		redirect_back( fallback_location: '/admin' )
	end

	def index
		@allowance = Allowance.first
		
		sort_by = params[:sort_by] || 'updated_at'
		sort_dir = params[:sort_dir] || 'desc'

		@transactions = @allowance.allowance_transactions.order( "#{sort_by} #{sort_dir}" )
		
		@transactions = @transactions.page( params[:page] )

	end


	def update_allowance
		@allowance = Allowance.first
		@allowance.amount = params[:amount].to_f * 100
		@allowance.interval_unit = params[:interval_unit]
		@allowance.interval_value = params[:interval_value]
		@allowance.status = params[:status]
		@allowance.save
		redirect_back( fallback_location: '/admin' )
	end


	def update
		@transaction.attributes = transaction_params
		@transaction.amount = transaction_params[:amount].to_f * 100
		@transaction.save
		redirect_back( fallback_location: '/admin' )
	end




	private

		def get_transaction
			@transaction = Allowance.first.allowance_transactions.find( params[:id] )
		end

		def transaction_params
			params.require( :allowance_transaction ).permit( :title, :amount, :notes )
		end

		def require_momdad
			unless current_user.momdad?
				redirect_to '/admin'
				return false
			end
		end

end

app/views/allowance_admin/_new_modal.html.haml
#new_transaction.modal.fade
	.modal-dialog
		.modal-content
			.modal-header
				%button.close{ type: :button, 'data-dismiss' => 'modal', 'aria-hidden' => 'true' }
					&times;
				%h4.modal-title
					Add/Subtract Money
			= form_for AllowanceTransaction.new, url: main_app.allowance_admin_index_path do |f|
				.modal-body
					.row
						.col-sm-8
							= f.label :title
							= f.text_field :title, class: 'form-control'
						.col-sm-4

							= f.label :amount
							.input-group
								%span.input-group-addon
									$
								= f.text_field :amount, class: 'form-control'
					.row
						.col-sm-12
							= f.label :notes
							= f.text_area :notes, class: 'form-control'
				.modal-footer
					%button.btn.btn-default{ type: :button, 'data-dismiss' => 'modal' }
						Close
					= f.submit 'Create', class: 'btn btn-primary'

app/views/allowance_admin/edit.html.haml
.container-fluid
	.row
		.col-xs-10
			%ul.breadcrumb
				%li
					= link_to 'Admin', swell_media.admin_index_path
				%li
					= link_to 'Allowance Admin', allowance_admin_index_path
				%li
					%strong
						Edit
						= @transaction.title
		.col-xs-2
			

	= form_for @transaction, url: allowance_admin_path( @transaction ) do |f|

		.row
			.col-xs-8
				.form-group
					= f.label :title
					= f.text_field :title, class: 'form-control'


			
				.form-group
					= f.label :notes
					= f.text_area :notes, class: 'form-control'

				

			.col-xs-4
				.well
					
					.form-group
						= f.label :amount
						.input-group
							%span.input-group-addon
								$
							= f.text_field :amount, value: number_with_precision( (@transaction.amount.to_f / 100 ), :precision => 2 ), class: 'form-control'
					
					.form-group
						= f.submit 'Update', class: 'btn btn-primary'

app/views/allowance_admin/index.html.haml
.container-fluid
	.row
		.col-xs-10
			%ul.breadcrumb
				%li
					= link_to 'Admin', swell_media.admin_index_path
				%li
					%strong
						Allowance Admin

		.col-xs-2
			%a.btn.btn-success{ data: { toggle: :modal, target: '#new_transaction' } }
				%i.fa.fa-plus-square
				New
	.row
		.col-xs-6
			= raw paginate @transactions
		.col-xs-6

	.row
		= form_tag update_allowance_allowance_admin_path( @allowance ) do
			.col-sm-2
				.form-group
					Amount
					%br
					.input-group
						%span.input-group-addon
							$
						= text_field_tag :amount, '', value: number_with_precision( (@allowance.amount.to_f / 100 ), :precision => 2 ), class: 'form-control'
			.col-sm-2
				.form-group
					Every
					%br
					= text_field_tag :interval_value, '', value: @allowance.interval_value, class: 'form-control'
			.col-sm-3
				.form-group
					%br
					= select_tag :interval_unit, options_for_select( ['day', 'week', 'month'], @allowance.interval_unit ), class: 'form-control'
			.col-sm-3
				.form-group
					Status
					%br
					= select_tag :status, options_for_select( [ 'inactive', 'active', 'hold' ], @allowance.status ), class: 'form-control'
			.col-sm-2
				.form-group
					%br
					= submit_tag 'Enter', class: 'btn btn-primary'

	.row
		.col-xs-12
			%table.table
				%thead
					%th
						Title
						%a{ href: allowance_admin_index_path( sort_by: 'title', sort_dir: 'asc' ) }
							%i.fa.fa-arrow-up
						%a{ href: allowance_admin_index_path( sort_by: 'title', sort_dir: 'desc' ) }
							%i.fa.fa-arrow-down
					
					%th
						At
						%a{ href: allowance_admin_index_path( sort_by: 'created_at', sort_dir: 'asc' ) }
							%i.fa.fa-arrow-up
						%a{ href: allowance_admin_index_path( sort_by: 'created_at', sort_dir: 'desc' ) }
							%i.fa.fa-arrow-down

					%th
						Amount
						%a{ href: allowance_admin_index_path( sort_by: 'amount', sort_dir: 'asc' ) }
							%i.fa.fa-arrow-up
						%a{ href: allowance_admin_index_path( sort_by: 'amount', sort_dir: 'desc' ) }
							%i.fa.fa-arrow-down

					
					%th
						Balance

				%tbody
					- @transactions.each do |transaction|
						%tr
							%td
								= link_to transaction.title, edit_allowance_admin_path( transaction.id )

							%td
								= transaction.updated_at

							%td
								%span{ style: transaction.amount > 0 ? "color:#000;" : "color:#f00" }
									= number_to_currency( transaction.amount.to_f / 100 )
				
							%td
								= number_to_currency( transaction.balance.to_f / 100 )




= render 'new_modal'