config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :allowance_admin do 
  	post :update_allowance, on: :member
  end
  resources :allowance


  get "/art/in/:cat", to: 'art#index'
  get "/art/tagged/:tag", to: 'art#index'

  resources :art
  resources :art_admin do 
  	get :preview, on: :member
  	delete :empty_trash, on: :collection
  end

  get "/writings/in/:cat", to: 'writings#index'
  get "/writings/tagged/:tag", to: 'writings#index'

  resources :writings
  resources :writing_admin do 
  	get :preview, on: :member
  	delete :empty_trash, on: :collection
  end


  get '/about' => 'swell_media/static#about'

	devise_scope :user do
		get '/login' => 'sessions#new', as: 'login'
		get '/logout' => 'sessions#destroy', as: 'logout'
		get '/register' => 'registrations#new', as: 'register'
	end
	devise_for :users, :controllers => { :registrations => 'registrations', :sessions => 'sessions' }




  mount SwellMedia::Engine, :at => '/'
end

app/controllers/writing_admin_controller.rb
class WritingAdminController < SwellMedia::AdminController
	
	before_action :get_article, except: [ :create, :empty_trash, :index ]
	
	def create
		authorize( SwellMedia::Article, :admin_create? )
		@article = SwellMedia::Article.new( article_params )
		@article.publish_at ||= Time.zone.now
		@article.user ||= current_user
		@article.status = 'draft'

		if params[:article][:category_name].present?
			@article.category = SwellMedia::ArticleCategory.where( name: params[:article][:category_name] ).first_or_create( status: 'active' )
		end

		if @article.save
			set_flash 'Article Created'
			redirect_to edit_writing_admin_path( @article )
		else
			set_flash 'Article could not be created', :error, @article
			redirect_back( fallback_location: '/admin' )
		end
	end


	def destroy
		authorize( SwellMedia::Article, :admin_destroy? )
		@article.trash!
		set_flash 'Article Deleted'
		redirect_back( fallback_location: '/admin' )
	end


	def edit
		authorize( @article, :admin_edit? )
	end

	def empty_trash
		authorize( SwellMedia::Article, :admin_empty_trash? )
		@articles = SwellMedia::Article.trash.destroy_all
		redirect_back( fallback_location: '/admin' )
		set_flash "#{@articles.count} destroyed"
	end


	def index
		authorize( SwellMedia::Article, :admin? )
		sort_by = params[:sort_by] || 'publish_at'
		sort_dir = params[:sort_dir] || 'desc'

		@articles = SwellMedia::Article.order( "#{sort_by} #{sort_dir}" )

		if params[:status].present? && params[:status] != 'all'
			@articles = eval "@articles.#{params[:status]}"
		end

		if params[:q].present?
			@articles = @articles.where( "array[:q] && keywords", q: params[:q].downcase )
		end

		@articles = @articles.page( params[:page] )
	end


	def preview
		authorize( @article, :admin_preview? )
		@media = @article

		@media_comments = SwellSocial::UserPost.active.where( parent_obj_id: @media.id, parent_obj_type: @media.class.name ).order( created_at: :desc ) if defined?( SwellSocial )

		layout = @media.class.name.underscore.pluralize
		layout = @media.layout if @media.layout.present?
		
		render "swell_media/articles/show", layout: layout
	end


	def update
		authorize( @article, :admin_update? )
		
		@article.slug = nil if ( params[:article][:title] != @article.title ) || ( params[:article][:slug_pref].present? )

		@article.attributes = article_params
		@article.avatar_urls = params[:article][:avatar_urls] if params[:article].present? && params[:article][:avatar_urls].present?


		if params[:article][:category_name].present?
			@article.category = SwellMedia::ArticleCategory.where( name: params[:article][:category_name] ).first_or_create( status: 'active' )
		end

		if @article.save
			set_flash 'Article Updated'
			redirect_to edit_writing_admin_path( id: @article.id )
		else
			set_flash 'Article could not be Updated', :error, @article
			render :edit
		end
		
	end


	private
		def article_params
			params.require( :article ).permit( :title, :subtitle, :slug_pref, :description, :content, :category_id, :status, :publish_at, :show_title, :is_commentable, :user_id, :tags, :tags_csv, :avatar, :avatar_asset_file, :avatar_asset_url, :cover_image, :avatar_urls, :redirect_url )
		end

		def get_article
			@article = SwellMedia::Article.friendly.find( params[:id] )
		end

end

app/views/writing_admin/_new_modal.html.haml
#new_article.modal.fade
	.modal-dialog
		.modal-content
			.modal-header
				%button.close{ type: :button, 'data-dismiss' => 'modal', 'aria-hidden' => 'true' }
					&times;
				%h4.modal-title
					New Writing
			= form_for SwellMedia::Article.new, url: writing_admin_index_path do |f|
				.modal-body
					.form-group
						= f.label :title
						= f.text_field :title, class: 'form-control'
					.form-group
						= f.label :category_id
						= f.collection_select :category_id, SwellMedia::ArticleCategory.active.order( :name ), :id, :name, {}, class: 'form-control'
					.form-group
						= f.label :description
						= f.text_area :description, class: 'form-control'
				.modal-footer
					%button.btn.btn-default{ type: :button, 'data-dismiss' => 'modal' }
						Close
					= f.submit 'Create', class: 'btn btn-primary'

app/views/writing_admin/edit.html.haml
.container-fluid
	.row
		.col-xs-10
			%ul.breadcrumb
				%li
					= link_to 'Admin', swell_media.admin_index_path
				%li
					= link_to 'Writing Admin', writing_admin_index_path
				%li
					%strong
						Edit
						= @article.title
		.col-xs-2
			%a.btn.btn-primary{ href: preview_writing_admin_path( @article.id ), target: '_new' }
				%i.fa.fa-eye
				Preview

	= form_for @article, url: writing_admin_path( @article ) do |f|

		.row
			.col-xs-8
				.form-group
					= f.text_field :title, class: 'form-control input-lg'
				.form-group
					= f.label :subtitle
					= f.text_field :subtitle, class: 'form-control'

				-#.form-group
					= f.label :slug_pref, 'URL for this article:'
					.input-group
						%span.input-group-addon
							= SwellMedia.app_host
						= f.text_field :slug_pref, class: 'form-control', placeholder: @article.slug

					= f.label :redirect_url, 'Redirect to:'
					= f.text_field :redirect_url, class: 'form-control'


				.row
					.col-xs-4
						.form-group
							= f.label :avatar, 'Image (default):'
							= image_tag @article.avatar.to_s, class: 'img-responsive', id: 'article_avatar_img'
							%div{ style: 'text-align:center;padding:0.3em;' }
								%a{ href: '#', data: { toggle: :assetup, for: '#article_avatar,#article_avatar_img', asset: { asset_type: 'image', use: 'avatar', status: 'active', parent_obj_id: @article.id, parent_obj_type: @article.class.base_class.name }.to_json, params: { authenticity_token: form_authenticity_token() }.to_json } }
									%i.fa.fa-upload
									upload
							= f.hidden_field :avatar, class: 'form-control', id: 'article_avatar'
							-# = text_field_tag :avatar_text_field, '', class: 'form-control', placeholder: 'Full Path to Image', data: { inputfor: '#article_avatar_asset_url' }
					.col-xs-4
						.form-group
							= f.label :cover_image, 'Image (cover):'
							= image_tag @article.cover_image.to_s, class: 'img-responsive', id: 'article_cover_image_img'
							%div{ style: 'text-align:center;padding:0.3em;' }
								%a{ href: '#', data: { toggle: :assetup, for: '#article_cover_image, #article_cover_image_img', asset: { asset_type: 'image', use: 'avatar', status: 'active', parent_obj_id: @article.id, parent_obj_type: @article.class.base_class.name }.to_json, params: { authenticity_token: form_authenticity_token() }.to_json } }
									%i.fa.fa-upload
									upload
							= f.hidden_field :cover_image, class: 'form-control', id: 'article_cover_image'
							-# = text_field_tag :avatar_text_field, '', class: 'form-control', placeholder: 'Full Path to Image', data: { inputfor: '#article_avatar_asset_url' }
					-# SwellMedia.article_avatars.each do |avatar_name|
						.col-xs-4

							.form-group
								= f.label "avatar_#{avatar_name}", "Image (#{avatar_name}):"
								= image_tag @article.avatar_url( avatar_name.to_sym ), class: 'img-responsive', id: "article_avatar_#{avatar_name}_img"
								%div{ style: 'text-align:center;padding:0.3em;' }
									%a{ href: '#', data: { toggle: :assetup, for: "#article_avatar_#{avatar_name}_img, #article_avatar_asset_#{avatar_name}_url", asset: { asset_type: 'image', use: "avatar_#{avatar_name}", status: 'active', parent_obj_id: @article.id, parent_obj_type: @article.class.base_class.name }.to_json, params: { authenticity_token: form_authenticity_token() }.to_json } }
										%i.fa.fa-upload
										upload
								= hidden_field_tag "article[avatar_urls][#{avatar_name}]", @article.avatar_url( avatar_name.to_sym ), class: 'form-control', id: "article_avatar_asset_#{avatar_name}_url"


				.form-group
					= f.label :description, 'Summary'
					= f.text_area :description, class: 'form-control wysiwyg', data: { wysiwyg: { height_min: 100, toolbar_sticky: true, toolbar_preset: 'admin_default', asset_manager: swell_media.asset_manager_index_path( asset: { parent_obj_type: @article.class.name, parent_obj_id: @article.id }, request_forgery_protection_token.to_s => form_authenticity_token, response: :json ) }.to_json }

				.form-group
					= f.text_area :content, class: 'form-control wysiwyg', data: { wysiwyg: { height_min: 200, toolbar_sticky: true, toolbar_preset: 'admin_default', asset_manager: swell_media.asset_manager_index_path( asset: { parent_obj_type: @article.class.name, parent_obj_id: @article.id }, request_forgery_protection_token.to_s => form_authenticity_token, response: :json ) }.to_json }


			.col-xs-4
				.well
					-#.form-group
						= f.label :user_id, 'Author'
						= f.collection_select :user_id, SwellMedia.registered_user_class.constantize.where( "role > 1" ), :id, :name, {}, class: 'form-control'
					.form-group
						= f.label :publish_at
						= f.text_field :publish_at, value: current_user.to_local_tz( @article.publish_at ), class: 'form-control datetimepicker'
					.form-group
						= f.label :category_id
						= f.collection_select :category_id, SwellMedia::ArticleCategory.active.order( :name ), :id, :name, { include_blank: '-- None -- ' }, class: 'form-control'
					-#.form-group
						= f.text_field :category_name, class: 'form-control', placeholder: 'Add Category'
					.form-group
						= f.label :status
						= f.collection_select :status, SwellMedia::Article.statuses, :first, :first, {}, class: 'form-control'
					.form-group
						= f.label :availability
						= f.collection_select :availability, SwellMedia::Article.availabilities, :first, :first, {}, class: 'form-control'
					.form-group
						= f.label :tags_csv, 'Tags:'
						= f.text_field :tags_csv, placeholder: 'Separate tags with commas', class: 'form-control'
					-#.form-group
						= f.check_box :is_commentable, {}, 'true', 'false'
						Allow Comments?
					.form-group
						= f.submit 'Update', class: 'btn btn-primary'

app/views/writing_admin/index.html.haml
.container-fluid
	.row
		.col-xs-10
			%ul.breadcrumb
				%li
					= link_to 'Admin', swell_media.admin_index_path
				%li
					%strong
						Writing Admin
						= "(#{pluralize @articles.total_count, 'Item'})"

		.col-xs-2
			%a.btn.btn-success{ data: { toggle: :modal, target: '#new_article' } }
				%i.fa.fa-plus-square
				New
	.row
		.col-xs-6
			= raw paginate @articles
		.col-xs-6
			= form_tag writing_admin_index_path, method: :get, class: 'pull-right form-inline' do
				= select_tag :status, options_from_collection_for_select( SwellMedia::Article.statuses, :first, :first, params[:status] ), { prompt: "-- All --", class: 'form-control' }
				= text_field_tag :q, params[:q], class: 'form-control'
				= submit_tag 'Search', class: 'btn btn-primary'
				= link_to 'Clear', writing_admin_index_path, class: 'btn btn-default btn-xs'

	.row
		.col-xs-12
			%table.table
				%thead
					%th
					%th
						Title
						%a{ href: writing_admin_index_path( sort_by: 'title', sort_dir: 'asc' ) }
							%i.fa.fa-arrow-up
						%a{ href: writing_admin_index_path( sort_by: 'title', sort_dir: 'desc' ) }
							%i.fa.fa-arrow-down
					
					%th
						Publish
						%a{ href: writing_admin_index_path( sort_by: 'publish_at', sort_dir: 'asc' ) }
							%i.fa.fa-arrow-up
						%a{ href: writing_admin_index_path( sort_by: 'publish_at', sort_dir: 'desc' ) }
							%i.fa.fa-arrow-down

					%th
						Words
						%a{ href: writing_admin_index_path( sort_by: 'cached_word_count', sort_dir: 'asc' ) }
							%i.fa.fa-arrow-up
						%a{ href: writing_admin_index_path( sort_by: 'cached_word_count', sort_dir: 'desc' ) }
							%i.fa.fa-arrow-down

					%th Status
					%th Category
					%th Tags
					%th
				%tbody
					- @articles.each do |article|
						%tr
							%td
								= image_tag article.avatar.to_s, width: 50, class: 'img img-rounded'
							%td
								= link_to article.title, edit_writing_admin_path( article.id )
								%br
								= article.path
							%td
								= article.publish_at.to_s( :slashed_time )
							%td
								= article.try( :cached_word_count ) || 'N/A'
							%td
								- if article.published?
									.badge{ class: article.status }
										Live
								- elsif article.draft?
									.badge{ class: article.status }
										Draft
								- elsif article.active?
									.badge{ class: 'pending' }
										Pending
								- else
									.badge{ class: article.status }
										= article.status
							%td
								= article.category.try( :name ) || 'None'
							%td
								= article.tags.join(', ')
							%td
								.btn-group
									%button.btn.btn-mini.btn-default.dropdown-toggle{ data: { toggle: :dropdown } }
										%i.fa.fa-cog
										%b.caret
									%ul.dropdown-menu
										%li
											%a{ href: edit_writing_admin_path( article.id ) }
												%i.fa.fa-pencil
												Edit
										
										%li
											%a{ href: preview_writing_admin_path( article.id ) }
												%i.fa.fa-eye
												Preview
										%li.divider
										%li
											%a{ href: writing_admin_path( article ), data: { method: 'delete', confirm: 'Are you sure?' } }
												%i.fa.fa-trash-o
												Delete!

- if SwellMedia::Article.trash.present?
	.pull-right{ style: 'margin-right:2em;' }
		%a{ href: empty_trash_writing_admin_index_path, data: { method: 'delete', confirm: 'Are you sure?' } }
			%btn.btn.btn-danger
				empty trash

= render 'new_modal'