config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :allowance_admin do 
  	post :update_allowance, on: :member
  end
  resources :allowance


  get "/art/in/:cat", to: 'art#index'
  get "/art/tagged/:tag", to: 'art#index'

  resources :art
  resources :art_admin do 
  	get :preview, on: :member
  	delete :empty_trash, on: :collection
  end

  get "/writings/in/:cat", to: 'writings#index'
  get "/writings/tagged/:tag", to: 'writings#index'

  resources :writings
  resources :writing_admin do 
  	get :preview, on: :member
  	delete :empty_trash, on: :collection
  end


  get '/about' => 'swell_media/static#about'

	devise_scope :user do
		get '/login' => 'sessions#new', as: 'login'
		get '/logout' => 'sessions#destroy', as: 'logout'
		get '/register' => 'registrations#new', as: 'register'
	end
	devise_for :users, :controllers => { :registrations => 'registrations', :sessions => 'sessions' }




  mount SwellMedia::Engine, :at => '/'
end

app/controllers/art_admin_controller.rb
class ArtAdminController < SwellMedia::AdminController
	before_action :get_Art, except: [ :create, :empty_trash, :index ]
	
	def create
		authorize( Art, :admin_create? )
		@art = Art.new( art_params )
		@art.publish_at ||= Time.zone.now
		@art.user ||= current_user
		@art.status = 'draft'

		if params[:art][:category_name].present?
			@art.category = ArtCategory.where( name: params[:art][:category_name] ).first_or_create( status: 'active' )
		end

		if @art.save
			set_flash 'Art Created'
			redirect_to edit_art_admin_path( @art )
		else
			set_flash 'Art could not be created', :error, @art
			redirect_back( fallback_location: '/admin' )
		end
	end


	def destroy
		authorize( Art, :admin_destroy? )
		@art.trash!
		set_flash 'Art Deleted'
		redirect_back( fallback_location: '/admin' )
	end


	def edit
		authorize( @art, :admin_edit? )
	end

	def empty_trash
		authorize( Art, :admin_empty_trash? )
		@pictures = Art.trash.destroy_all
		redirect_back( fallback_location: '/admin' )
		set_flash "#{@pictures.count} destroyed"
	end


	def index
		authorize( Art, :admin? )
		sort_by = params[:sort_by] || 'publish_at'
		sort_dir = params[:sort_dir] || 'desc'

		@art = Art.order( "#{sort_by} #{sort_dir}" )

		if params[:status].present? && params[:status] != 'all'
			@art = eval "@art.#{params[:status]}"
		end

		if params[:q].present?
			@art = @art.where( "array[:q] && keywords", q: params[:q].downcase )
		end

		@art = @art.page( params[:page] )
	end


	def preview
		authorize( @Art, :admin_preview? )
		@media = @Art

		@media_comments = SwellSocial::UserPost.active.where( parent_obj_id: @media.id, parent_obj_type: @media.class.name ).order( created_at: :desc ) if defined?( SwellSocial )

		layout = @media.class.name.underscore.pluralize
		layout = @media.layout if @media.layout.present?
		
		render "art/show", layout: layout
	end


	def update
		authorize( @art, :admin_update? )
		
		@art.slug = nil if ( params[:art][:title] != @art.title ) || ( params[:art][:slug_pref].present? )

		@art.attributes = art_params
		@art.avatar_urls = params[:art][:avatar_urls] if params[:art].present? && params[:art][:avatar_urls].present?


		if params[:art][:category_name].present?
			@art.category = ArtCategory.where( name: params[:art][:category_name] ).first_or_create( status: 'active' )
		end

		if @art.save
			set_flash 'Art Updated'
			redirect_to edit_art_admin_path( id: @art.id )
		else
			set_flash 'Art could not be Updated', :error, @art
			render :edit
		end
		
	end


	private
		def art_params
			params.require( :art ).permit( :title, :subtitle, :slug_pref, :description, :content, :category_id, :status, :publish_at, :show_title, :is_commentable, :user_id, :tags, :tags_csv, :avatar, :avatar_asset_file, :avatar_asset_url, :cover_image, :avatar_urls, :redirect_url )
		end

		def get_Art
			@art = Art.friendly.find( params[:id] )
		end
end

app/views/art_admin/_new_modal.html.haml
#new_picture.modal.fade
	.modal-dialog
		.modal-content
			.modal-header
				%button.close{ type: :button, 'data-dismiss' => 'modal', 'aria-hidden' => 'true' }
					&times;
				%h4.modal-title
					Add Art
			= form_for Art.new, url: art_admin_index_path do |f|
				.modal-body
					.form-group
						= f.label :title
						= f.text_field :title, class: 'form-control'
					.form-group
						= f.label :category_id
						= f.collection_select :category_id, ArtCategory.active.order( :name ), :id, :name, {}, class: 'form-control'
					.form-group
						= f.label :description
						= f.text_area :description, class: 'form-control'
				.modal-footer
					%button.btn.btn-default{ type: :button, 'data-dismiss' => 'modal' }
						Close
					= f.submit 'Create', class: 'btn btn-primary'

app/views/art_admin/edit.html.haml
.container-fluid
	.row
		.col-xs-10
			%ul.breadcrumb
				%li
					= link_to 'Admin', swell_media.admin_index_path
				%li
					= link_to 'Art Admin', art_admin_index_path
				%li
					%strong
						Edit
						= @art.title
		.col-xs-2
			%a.btn.btn-primary{ href: preview_art_admin_path( @art.id ), target: '_new' }
				%i.fa.fa-eye
				Preview

	= form_for @art, url: art_admin_path( @art ) do |f|

		.row
			.col-xs-8
				.form-group
					= f.text_field :title, class: 'form-control input-lg'


				-#.form-group
					= f.label :slug_pref, 'URL for this art:'
					.input-group
						%span.input-group-addon
							= SwellMedia.app_host
						= f.text_field :slug_pref, class: 'form-control', placeholder: @art.slug

					= f.label :redirect_url, 'Redirect to:'
					= f.text_field :redirect_url, class: 'form-control'


				.row
					.col-xs-10.col-xs-offset-1
						.form-group
							= f.label :avatar, 'Image (default):'
							= image_tag @art.avatar.to_s, class: 'img-responsive', id: 'art_avatar_img'
							%div{ style: 'text-align:center;padding:0.3em;' }
								%a{ href: '#', data: { toggle: :assetup, for: '#art_avatar,#art_avatar_img', asset: { asset_type: 'image', use: 'avatar', status: 'active', parent_obj_id: @art.id, parent_obj_type: @art.class.base_class.name }.to_json, params: { authenticity_token: form_authenticity_token() }.to_json } }
									%i.fa.fa-upload
									upload
							= f.hidden_field :avatar, class: 'form-control', id: 'art_avatar'
							-# = text_field_tag :avatar_text_field, '', class: 'form-control', placeholder: 'Full Path to Image', data: { inputfor: '#art_avatar_asset_url' }
					


				.form-group
					= f.label :description
					= f.text_area :description, class: 'form-control wysiwyg', data: { wysiwyg: { height_min: 100, toolbar_sticky: true, toolbar_preset: 'admin_default', asset_manager: swell_media.asset_manager_index_path( asset: { parent_obj_type: @art.class.name, parent_obj_id: @art.id }, request_forgery_protection_token.to_s => form_authenticity_token, response: :json ) }.to_json }

			

			.col-xs-4
				.well
					-#.form-group
						= f.label :user_id, 'Author'
						= f.collection_select :user_id, SwellMedia.registered_user_class.constantize.where( "role > 1" ), :id, :name, {}, class: 'form-control'
					.form-group
						= f.label :publish_at
						= f.text_field :publish_at, value: current_user.to_local_tz( @art.publish_at ), class: 'form-control datetimepicker'
					.form-group
						= f.label :category_id
						= f.collection_select :category_id, ArtCategory.active.order( :name ), :id, :name, { include_blank: '-- None -- ' }, class: 'form-control'
					.form-group
						= f.text_field :category_name, class: 'form-control', placeholder: 'Add Category'
					.form-group
						= f.label :status
						= f.collection_select :status, Art.statuses, :first, :first, {}, class: 'form-control'
					.form-group
						= f.label :availability
						= f.collection_select :availability, Art.availabilities, :first, :first, {}, class: 'form-control'
					.form-group
						= f.label :tags_csv, 'Tags:'
						= f.text_field :tags_csv, placeholder: 'Separate tags with commas', class: 'form-control'
					-#.form-group
						= f.check_box :is_commentable, {}, 'true', 'false'
						Allow Comments?
					.form-group
						= f.submit 'Update', class: 'btn btn-primary'

app/views/art_admin/index.html.haml
.container-fluid
	.row
		.col-xs-10
			%ul.breadcrumb
				%li
					= link_to 'Admin', swell_media.admin_index_path
				%li
					%strong
						Art Admin
						= "(#{pluralize @art.total_count, 'Art Work'})"

		.col-xs-2
			%a.btn.btn-success{ data: { toggle: :modal, target: '#new_art' } }
				%i.fa.fa-plus-square
				New
	.row
		.col-xs-6
			= raw paginate @art
		.col-xs-6
			= form_tag art_admin_index_path, method: :get, class: 'pull-right form-inline' do
				= select_tag :status, options_from_collection_for_select( Art.statuses, :first, :first, params[:status] ), { prompt: "-- All --", class: 'form-control' }
				= text_field_tag :q, params[:q], class: 'form-control'
				= submit_tag 'Search', class: 'btn btn-primary'
				= link_to 'Clear', art_admin_index_path, class: 'btn btn-default btn-xs'

	.row
		.col-xs-12
			%table.table
				%thead
					%th
					%th
						Title
						%a{ href: art_admin_index_path( sort_by: 'title', sort_dir: 'asc' ) }
							%i.fa.fa-arrow-up
						%a{ href: art_admin_index_path( sort_by: 'title', sort_dir: 'desc' ) }
							%i.fa.fa-arrow-down
					
					%th
						Publish
						%a{ href: art_admin_index_path( sort_by: 'publish_at', sort_dir: 'asc' ) }
							%i.fa.fa-arrow-up
						%a{ href: art_admin_index_path( sort_by: 'publish_at', sort_dir: 'desc' ) }
							%i.fa.fa-arrow-down

					%th Status
					%th Category
					%th Tags
					%th
				%tbody
					- @art.each do |art|
						%tr
							%td
								= image_tag art.avatar.to_s, width: 50, class: 'img img-rounded'
							%td
								= link_to art.title, edit_art_admin_path( art.id )
								%br
								= art.path
							%td
								= art.publish_at.to_s( :slashed_time )

							%td
								- if art.published?
									.badge{ class: art.status }
										Live
								- elsif art.draft?
									.badge{ class: art.status }
										Draft
								- elsif art.active?
									.badge{ class: 'pending' }
										Pending
								- else
									.badge{ class: art.status }
										= art.status
							%td
								= art.category.try( :name ) || 'None'
							%td
								= art.tags.join(', ')
							%td
								.btn-group
									%button.btn.btn-mini.btn-default.dropdown-toggle{ data: { toggle: :dropdown } }
										%i.fa.fa-cog
										%b.caret
									%ul.dropdown-menu
										%li
											%a{ href: edit_art_admin_path( art.id ) }
												%i.fa.fa-pencil
												Edit
										
										%li
											%a{ href: preview_art_admin_path( art.id ) }
												%i.fa.fa-eye
												Preview
										%li.divider
										%li
											%a{ href: art_admin_path( art ), data: { method: 'delete', confirm: 'Are you sure?' } }
												%i.fa.fa-trash-o
												Delete!

- if Art.trash.present?
	.pull-right{ style: 'margin-right:2em;' }
		%a{ href: empty_trash_art_admin_index_path, data: { method: 'delete', confirm: 'Are you sure?' } }
			%btn.btn.btn-danger
				empty trash

= render 'new_modal'